services:
 
  myportfolio:
    build:
      #This is were the Dockerfile path is.. Root Directory
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network
 
  db:
    image: mysql:8.0
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: my_db
    volumes:
      - mysql-data:/var/lib/msql
    ports:
      - '3306:3306'
    networks:
      - app-network
 
  adminer:
    image: adminer
    ports:
      - '8081:8080'
    depends_on:
      - db
    networks:
      - app-network
 
volumes:
  mysql-data:
 
networks:
  app-network:
    driver: bridge
 